<a href="https://colab.research.google.com/github/ashaycclub/100DaysOfMLCode/blob/master/Bert_UStech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install transformers


     |████████████████████████████████| 573kB 3.5MB/s 
     |████████████████████████████████| 1.0MB 13.5MB/s 
     |████████████████████████████████| 3.7MB 24.3MB/s 
     |████████████████████████████████| 890kB 32.9MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.41-cp36-none-any.whl size=893334 sha256=eea50aa58ec83d0b1ba169510f2cc494e9e72ca35277d21185db119360e8c8d3
  Stored in directory: /root/.cache/pip/wheels/22/5a/d4/b020a81249de7dc63758a34222feaa668dbe8ebfe9170cc9b1
Successfully built sacremoses


In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
import warnings
warnings.filterwarnings('ignore')

## Importing the dataset
We'll use pandas to read the dataset and load it into a dataframe.

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
cd /content/drive/My Drive/bert_data

/content/drive/My Drive/bert_data


In [0]:
value=1
np.random.seed(value)

In [0]:
with open('test.csv','r') as f:
    data=f.readlines()

FileNotFoundError: ignored

In [0]:
data

['heading\n',
 'prior employment\n',
 'exceptional team work\n',
 'qualification statement published on businessweek.com\n',
 'associates degree in english\n',
 'advanced statistics\n',
 'motorboat qualification course\n',
 'chinese studies\n',
 'quick view\n',
 'scholarship\n',
 'inventories\n',
 'basic information\n',
 'program by\n',
 'work permit policies\n',
 'clerical duties\n',
 'programs\n',
 'outreach services\n',
 'competition\n',
 'naturescape\n',
 'citations\n',
 'peer-reviewed publications\n',
 'funding\n',
 'relevant course work\n',
 'coursework includes\n',
 'reference title\n',
 'past due\n',
 'quality improvement plans\n',
 'seeking employment\n',
 'drug use and abuse\n',
 'child time\n',
 'national diploma\n',
 'knowledge\n',
 'dissertation\n',
 'book personal appointments\n',
 'volunteer work between jobs\n',
 'sawyer school diploma\n',
 'secure & coordinate proctor exams\n',
 'definitions\n',
 'independent research\n',
 'needs assessments\n',
 'specialized training\

In [0]:
import re
c=[]
for val in data:
    c.append(re.sub('\W+','', val ))

In [0]:
c

['heading',
 'prioremployment',
 'exceptionalteamwork',
 'qualificationstatementpublishedonbusinessweekcom',
 'associatesdegreeinenglish',
 'advancedstatistics',
 'motorboatqualificationcourse',
 'chinesestudies',
 'quickview',
 'scholarship',
 'inventories',
 'basicinformation',
 'programby',
 'workpermitpolicies',
 'clericalduties',
 'programs',
 'outreachservices',
 'competition',
 'naturescape',
 'citations',
 'peerreviewedpublications',
 'funding',
 'relevantcoursework',
 'courseworkincludes',
 'referencetitle',
 'pastdue',
 'qualityimprovementplans',
 'seekingemployment',
 'druguseandabuse',
 'childtime',
 'nationaldiploma',
 'knowledge',
 'dissertation',
 'bookpersonalappointments',
 'volunteerworkbetweenjobs',
 'sawyerschooldiploma',
 'securecoordinateproctorexams',
 'definitions',
 'independentresearch',
 'needsassessments',
 'specializedtraining',
 'minors',
 'nonprofitleadershipandaccomplishment',
 'solicitationagreements',
 'socialreport',
 'claimantinterviews',
 'emphasisi

In [0]:
with open('data.txt','w') as d:
    d.write(str(c))

In [0]:
df = pd.read_csv('test.csv',encoding='latin-1')

In [0]:
df.head()

data   Class
0                                      Suresh Kumar       0
1  E Mail bskumar_ash@yahoo.com ~ Contact +91 960...      0
2  Seeking assignments Technology Leader organiza...      4
3  Technical Leader More 14 years expertise leadi...      3
4                       Lastly worked SIS India Pvt       1

In [0]:
df.isnull().sum()

data     0
Class    0
dtype: int64

In [0]:
df.size

12938

In [0]:
i=[df['class'].isnull()]


In [0]:
len(i[0])

6469

Listing index with nan values
Dropping the values 

In [0]:
for val in range(len(i[0])):
  if (i[0][val]==True):
    print(val)

1277
1278
1279


In [0]:
df.dropna(axis=0,inplace=True)


In [0]:
df.shape

(6469, 2)

### data is now well formatted for use



In [0]:
df.isnull().sum()

 Data    0
class    0
dtype: int64

## Listing class wise values out of 402

In [0]:
df['class'].value_counts()

1    3789
0    2680
Name: class, dtype: int64

#### Save for later use


In [0]:
df.to_csv('use.csv')

In [0]:
file=pd.read_csv('use.csv')

### Filtered multiple occurences of file but the class is still imbalanced


1.   Can't depend on just accuracy
2.   May need more data for minority class or use sampling technique





In [0]:
file['class'].value_counts()

0.0    830
1.0    447
Name: class, dtype: int64

In [0]:
file=df

## Parameters to trust ( *Not Accuracy*)


---


*   Precision
*   Balanced Accuracy

*   Recall 
*   F1 Score






In [0]:
batch_1=file

## Loading the Pre-trained BERT model


In [0]:
# For DistilBERT:
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer, 'distilbert-base-uncased')

## To use base model use
#model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

In [0]:
file.columns

Index(['data ', 'Class'], dtype='object')

In [0]:
file['data ']

0                                          Suresh Kumar 
1      E Mail bskumar_ash@yahoo.com ~ Contact +91 960...
2      Seeking assignments Technology Leader organiza...
3      Technical Leader More 14 years expertise leadi...
4                           Lastly worked SIS India Pvt 
                             ...                        
396                             Academic Qualifications 
397    Bachelor Technology Computer Science & Enginee...
398                                    Personal details 
399    Date birth Marital Status Permanent Address Pa...
400    Flat No 36 GH8 Paschim Vihar Near Meera Bagh N...
Name: data , Length: 401, dtype: object

In [0]:
tokenized = file['data '].apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))



*   adds <(cls)> token

*   adds <(seq)> token
*   adds ## for words contained in middle of the sentence





In [0]:
max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)

padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])

Our dataset is now in the `padded` variable, we can view its dimensions below:

In [0]:
np.array(padded).shape

(401, 88)

In [0]:
view=pd.DataFrame(padded)

## Padding is done to make all inputs of same size 

In [0]:
view.tail(10)

0     1      2      3      4      5      6   ...  81  82  83  84  85  86  87
391  101  8325   4730  16129   2629   9262  22483  ...   0   0   0   0   0   0   0
392  101  2363  17205   2400   5151   2836   5038  ...   0   0   0   0   0   0   0
393  101  1996  27218   8840  11266   2953   4037  ...   0   0   0   0   0   0   0
394  101  2363   8196   5887   2132   7070   6691  ...   0   0   0   0   0   0   0
395  101  3018   8196   6566   2267  12329   3416  ...   0   0   0   0   0   0   0
396  101  3834  15644    102      0      0      0  ...   0   0   0   0   0   0   0
397  101  5065   2974   3274   2671   1004   3330  ...   0   0   0   0   0   0   0
398  101  3167   4751    102      0      0      0  ...   0   0   0   0   0   0   0
399  101  3058   4182  23143   3570   4568   4769  ...   0   0   0   0   0   0   0
400  101  4257   2053   4029   1043   2232   2620  ...   0   0   0   0   0   0   0

[10 rows x 88 columns]

In [0]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape

(401, 88)

In [0]:
input_ids = torch.tensor(padded)  
attention_mask = torch.tensor(attention_mask)

with torch.no_grad():
    last_hidden_states = model(input_ids, attention_mask=attention_mask)

In [0]:
features = last_hidden_states[0][:,0,:].numpy()

In [0]:
labels = file['class']

KeyError: ignored

In [0]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels)

In [0]:
 parameters = {'C': np.linspace(0.0001, 100, 20)}
 grid_search = GridSearchCV(LogisticRegression(), parameters)
 grid_search.fit(train_features, train_labels)

 print('best parameters: ', grid_search.best_params_)
 print('best scrores: ', grid_search.best_score_)

ValueError: ignored

In [0]:
lr_clf = LogisticRegression(C=5.263252631578947)
lr_clf.fit(train_features, train_labels)

ValueError: ignored

In [0]:
lr_clf.score(test_features, test_labels)

AttributeError: ignored

In [0]:
len(test_features)

1618

In [0]:
y_pred=lr_clf.predict(test_features)

In [0]:
len(y_pred)

1618

In [0]:
test_labels

2704    1
6381    1
1731    0
1307    0
5688    1
       ..
6252    1
5764    1
996     0
4249    1
3908    1
Name: class, Length: 1618, dtype: int64

In [0]:
from sklearn.metrics import classification_report as clfr

In [0]:
print(clfr(test_labels,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.90      0.88       654
           1       0.93      0.89      0.91       964

    accuracy                           0.90      1618
   macro avg       0.89      0.90      0.89      1618
weighted avg       0.90      0.90      0.90      1618



Personal Info  0 <br>
Organization   1<br>
Education      2<br>
Skills         3<br>
Others         4




In [0]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state = 42)
from pprint import pprint

In [0]:
model=RandomForestRegressor()
model.fit(train_features, train_labels)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [0]:
model.score(test_features, test_labels)

0.5367943734485058

In [0]:
from sklearn.ensemble import GradientBoostingClassifier
model_ad = GradientBoostingClassifier()
model_ad.fit(train_features, train_labels)
y_pred = model_ad.predict(test_features)



In [0]:
print(clfr(test_labels,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.84      0.82       654
           1       0.89      0.85      0.87       964

    accuracy                           0.85      1618
   macro avg       0.84      0.85      0.84      1618
weighted avg       0.85      0.85      0.85      1618



In [0]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [0]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy

In [0]:
base_model = RandomForestRegressor(n_estimators = 10, random_state = 42)
base_model.fit(train_features, train_labels)
base_accuracy = evaluate(base_model, test_features, test_labels)

In [0]:
best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random, test_features, test_labels)

In [0]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

In [0]:
model=XGBClassifier()

In [0]:
model.fit(train_features, train_labels)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
model.score()

0.8504326328800988

In [0]:
y_pred=model.predict(test_features)

In [0]:
print(clfr(test_labels,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.86      0.82       654
           1       0.90      0.85      0.87       964

    accuracy                           0.85      1618
   macro avg       0.84      0.85      0.85      1618
weighted avg       0.85      0.85      0.85      1618



In [0]:
# port warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBClassifier

In [0]:
from sklearn.ensemble import ExtraTreesClassifier

In [0]:
xgb = ExtraTreesClassifier()

In [0]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))
Y = train_labels
X = train_features
test = test_features


In [0]:
params = {
        'min_child_weight': [1, 5, 10,15],
        'gamma': [0.5, 1, 1.5, 2, 5],
        'subsample': [0.2,0.4,0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3, 4, 5,7]
        }

In [0]:
print('\n All results:')
print(random_search.cv_results_)
print('\n Best estimator:')
print(random_search.best_estimator_)
print('\n Best normalized gini score for %d-fold search with %d parameter combinations:' % (folds, param_comb))
print(random_search.best_score_ * 2 - 1)
print('\n Best hyperparameters:')
print(random_search.best_params_)
# results = pd.DataFrame(random_search.cv_results_)
# results.to_csv('xgb-random-grid-search-results-01.csv', index=False)


 All results:
{'mean_fit_time': array([166.35553985,  63.54143362,  78.207616  , 123.78636122,
       143.60517612, 198.61984539]), 'std_fit_time': array([0.67309725, 0.2735718 , 0.08096031, 0.29874651, 0.61647237,
       0.59071763]), 'mean_score_time': array([0.04591093, 0.03530955, 0.04135141, 0.05153961, 0.0417522 ,
       0.05249133]), 'std_score_time': array([0.00069444, 0.00031083, 0.00034959, 0.00049729, 0.000185  ,
       0.00056095]), 'param_subsample': masked_array(data=[0.6, 0.2, 0.4, 0.6, 0.8, 0.6],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_min_child_weight': masked_array(data=[15, 5, 5, 5, 1, 5],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_depth': masked_array(data=[7, 4, 5, 7, 5, 7],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_gamma': masked_a

In [0]:
xgb = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1.0, gamma=0.5,
              learning_rate=0.02, max_delta_step=0, max_depth=7,
              min_child_weight=5, missing=None, n_estimators=600, n_jobs=1,
              nthread=1, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=True, subsample=0.6, verbosity=1)

In [0]:
xgb.fit(train_features,train_labels)
xgb.score(test_features,test_labels)

0.8498145859085291

In [0]:
import pickle 
# Dump the trained decision tree classifier with Pickle
decision_tree_pkl_filename = 'Xgboost.pkl'
# Open the file to save as pkl file
decision_tree_model_pkl = open(decision_tree_pkl_filename, 'wb')
pickle.dump(xgb, decision_tree_model_pkl)
# Close the pickle instances
decision_tree_model_pkl.close()


In [0]:

# Loading the saved decision tree model pickle
decision_tree_model_pkl = open(decision_tree_pkl_filename, 'rb')
decision_tree_model = pickle.load(decision_tree_model_pkl)

In [0]:
decision_tree_model.score(test_features,test_labels)

0.8850432632880099

In [0]:
import numpy as np
import pandas as pd
import torch
import transformers as ppb
import pickle
pkl_filename = "Xgboost.pkl"


with open(pkl_filename, 'rb') as file:
	pickle_model = pickle.load(file)
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer, 'distilbert-base-uncased')
model = model_class.from_pretrained(pretrained_weights)

#model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)	

def heading_predict(x):   

  heading_extracted=[]   
  headings=pd.DataFrame(x,columns=['heading'])
  tokenization = headings['heading'].apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))
  max_len = 0
  for i in tokenization.values:
    if len(i) > max_len:
        max_len = len(i)

  # Heading list converted to numpy arrays for prediction 
  padded = np.array([i + [0]*(max_len-len(i)) for i in tokenization.values])
  attention_mask = np.where(padded != 0, 1, 0)
  input_ids = torch.tensor(padded)  
  attention_mask = torch.tensor(attention_mask)

  with torch.no_grad():
      last_hidden_states = model(input_ids, attention_mask=attention_mask)
      test = last_hidden_states[0][:,0,:] 
  predictions=pickle_model.predict(test)
  for i in range(len(predictions)):
    if int(predictions[i])==1:
      heading_extracted.append(x[i])
  return heading_extracted  

In [0]:
heading_predict(l)

['education']

In [0]:
estimator = XGBClassifier(
    objective= 'binary:logistic',
    nthread=4,
    seed=42
)

In [0]:
parameters = {
    'max_depth': range (2, 10, 1),
    'n_estimators': range(60, 220, 40),
    'learning_rate': [0.1, 0.01, 0.05]
}

In [0]:
grid_search = GridSearchCV(
    estimator=estimator,
    param_grid=parameters,
    scoring = 'roc_auc',
    n_jobs = 10,
    cv = 10,
    verbose=True
)

In [0]:
grid_search.best_estimator_

# Using better classifiers

In [0]:
!pip install simpletransformers



In [0]:
from simpletransformers.classification import ClassificationModel

In [0]:
par={'num_train_epochs': 1,'best_model_dir': 'outputs/best_model'}

In [0]:
from keras.models import load_model

In [0]:
from keras.models import Sequential

In [0]:
model = ClassificationModel('bert', 'bert-base-cased', num_labels=1,use_cuda=False)
# model.train_model(train_df=train,output_dir=,eval_df=test ) 
# model.save_model('f.h5')


In [0]:
file.columns

Index(['data ', 'Class'], dtype='object')

In [0]:
df['Class'].value_counts()

4    289
3     48
1     34
2     15
0     15
Name: Class, dtype: int64

In [0]:
model.args

{'adam_epsilon': 1e-08,
 'best_model_dir': 'outputs/best_model',
 'cache_dir': 'cache_dir/',
 'config': {},
 'do_lower_case': False,
 'early_stopping_delta': 0,
 'early_stopping_metric': 'eval_loss',
 'early_stopping_metric_minimize': True,
 'early_stopping_patience': 3,
 'encoding': None,
 'eval_batch_size': 8,
 'evaluate_during_training': False,
 'evaluate_during_training_steps': 2000,
 'evaluate_during_training_verbose': False,
 'fp16': False,
 'fp16_opt_level': 'O1',
 'gradient_accumulation_steps': 1,
 'learning_rate': 4e-05,
 'logging_steps': 50,
 'manual_seed': None,
 'max_grad_norm': 1.0,
 'max_seq_length': 128,
 'model_name': 'bert-base-cased',
 'model_type': 'bert',
 'n_gpu': 1,
 'no_cache': False,
 'num_train_epochs': 1,
 'output_dir': 'outputs/',
 'overwrite_output_dir': False,
 'process_count': 2,
 'regression': False,
 'reprocess_input_data': True,
 'save_eval_checkpoints': True,
 'save_model_every_epoch': True,
 'save_steps': 2000,
 'silent': False,
 'sliding_window': Fal

###  Training on 300 lines and to use new lines for predicting thr performance

In [0]:
# train=pd.read_csv('train.csv')
# test=pd.read_csv('test.csv')

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test=train_test_split(df,train_size=.70)

In [0]:
train=X_train
test=X_test

In [0]:
train=pd.DataFrame(train)

In [0]:
test=pd.DataFrame(test)

In [0]:
train

data   Class
342  Fathers Name Date Birth Nationality Sex Marita...      0
389  Developed component front end application usin...      4
39    Architecture SDLC Planning  Management  Under...      3
277  database objects Creating Table Writing SP Tri...      3
256  Windows Based Application Meeting onsite clien...      4
..                                                 ...    ...
71   Annexure Projects Handled Shipnet Software Sol...      1
129   VB .NET 11 Oracle SQL Server Windows 2000/XP ...      4
144  Given unique involvement across aspects media ...      4
335  Different MIS reports also available displayin...      4
133  This project maintenance project  involved enh...      4

[280 rows x 2 columns]

In [0]:
ls

'file3 (1).csv'   sample_data/


In [0]:
!mkdir new

In [0]:
from simpletransformers.classification import ClassificationModel

#Create a ClassificationModel
model = ClassificationModel('roberta', 'roberta-base', num_labels=5, use_cuda = False)


In [0]:
model.train_model(train)


Running loss: 0.840077



In [0]:
model.evaluate(test,output_dir='./outputs')

({'eval_loss': 0.8069420550018549, 'mcc': 0.0},
 array([[-1.6858571e+00, -1.0246930e-01, -1.1606736e+00,  2.0940205e-01,
          2.8638792e+00],
        [-1.7645686e+00,  4.6486687e-02, -1.2149910e+00,  3.9390358e-01,
          2.6566429e+00],
        [-1.3067373e+00, -3.9565988e-02, -1.0526925e+00,  4.5042768e-01,
          2.1822047e+00],
        [-1.6858571e+00, -1.0246930e-01, -1.1606736e+00,  2.0940205e-01,
          2.8638792e+00],
        [-1.6988932e+00, -4.9954813e-02, -1.2925028e+00,  2.5784406e-01,
          3.0321500e+00],
        [-1.7391686e+00,  3.6731429e-02, -1.1513939e+00,  4.0843278e-01,
          2.6070533e+00],
        [-1.3490989e+00,  1.0992667e-01, -1.1023837e+00,  4.5411754e-01,
          1.9968542e+00],
        [-1.6975062e+00,  3.0707594e-02, -1.1833055e+00,  1.8998879e-01,
          2.7016892e+00],
        [-1.5377917e+00,  1.6251458e-02, -1.1357719e+00,  6.4304590e-01,
          2.2858062e+00],
        [-1.4744709e+00,  5.4384638e-02, -1.0574944e+00,  4.5

In [0]:
cd heading_classifier/

/content/drive/My Drive/heading_classifier


In [0]:
result, model_outputs, wrong_predictions = model.eval_model(test)

In [0]:
result

{'eval_loss': 0.8464130610227585, 'mcc': 0.0}

In [0]:
model_outputs

array([[ 1.95568419e+00, -2.94334531e+00],
       [-8.44031394e-01,  1.35725808e+00],
       [-8.52615833e-01,  1.06495833e+00],
       [-8.84266555e-01,  1.06324506e+00],
       [ 2.19324994e+00, -3.01013565e+00],
       [-6.80717230e-01,  3.76625359e-01],
       [-5.32210529e-01,  1.32551134e-01],
       [ 5.67181468e-01, -1.13667071e+00],
       [ 1.44636965e+00, -2.31200099e+00],
       [ 2.01950026e+00, -2.99885941e+00],
       [ 1.68271530e+00, -2.70005989e+00],
       [-5.33708096e-01, -2.39178240e-02],
       [ 2.16635418e+00, -3.08715820e+00],
       [ 1.77049017e+00, -2.80076694e+00],
       [ 2.05453753e+00, -2.99608278e+00],
       [ 1.42313099e+00, -2.38037133e+00],
       [ 1.81092358e+00, -2.72513366e+00],
       [ 1.95817935e+00, -2.68549299e+00],
       [ 1.96125162e+00, -2.94752693e+00],
       [-3.40221137e-01, -1.32514328e-01],
       [-9.40237284e-01,  1.23969567e+00],
       [-1.10582089e+00,  1.48580945e+00],
       [ 1.44792295e+00, -2.41590405e+00],
       [ 1.

There are total 25 wrong predictions

In [0]:
len(wrong_predictions)

54

In [0]:
test.shape

(360, 2)

In [0]:
from sklearn.metrics import f1_score, accuracy_score
def f1_multiclass(labels, preds):
    return f1_score(labels, preds, average='micro')

In [0]:

scores2, model_outputs, wrong_predictions = model.eval_model(test, f1=f1_multiclass, acc=accuracy_score)

Converting to features started. Cache is not used.


{'mcc': 0.6867313953952584, 'tp': 103, 'tn': 203, 'fp': 41, 'fn': 13, 'eval_loss': 0.3098130907035536, 'f1': 0.85, 'acc': 0.85}


In [0]:
heading

245

In [0]:
validate=model.predict(heading)

Converting to features started. Cache is not used.


In [0]:
index=[]
for i in range(len(validate[0])):
  if validate[0][i]==0:
    index.append(i)work history


SyntaxError: ignored

In [0]:
len(index)

45

In [0]:
heading[15]

'position'

In [0]:
index

[0,
 15,
 20,
 22,
 29,
 31,
 39,
 43,
 44,
 48,
 66,
 73,
 84,
 85,
 86,
 88,
 94,
 95,
 103,
 104,
 105,
 107,
 116,
 131,
 134,
 141,
 142,
 143,
 146,
 148,
 155,
 163,
 166,
 174,
 178,
 189,
 190,
 193,
 194,
 195,
 198,
 201,
 221,
 225,
 243]

In [0]:
wrong=[]
for val in index:
  wrong.append(heading[val])

In [0]:
wrong

['Educated',
 'position',
 'personal profile',
 'Competency Matrix',
 'professional development',
 'objective',
 'academic',
 'certificates',
 'project annexure',
 'organisational experiance',
 'conference',
 'project overview',
 'achievement',
 'professional career',
 'career track',
 'contact details',
 'organisational scan',
 'educated',
 'work history',
 'Academic',
 'technical summary',
 'projects history',
 'employment history',
 'Professional Development',
 'certification',
 'credentials',
 'Technical Skill',
 'Publication',
 'employment',
 'Skill Set',
 'army courses',
 'introduction',
 'Organisational Scan',
 'competency matrix',
 'publication',
 'license and certifications',
 'professional summary',
 'Introduction',
 'profile summary',
 'Organisational Experiance',
 'professional profile',
 'Project Annexure',
 'ACADEMIC',
 'Conference',
 'CERTIFICATES']

In [0]:
predictions, raw_output  = model.predict(['skill'])

Converting to features started. Cache is not used.


In [0]:
predictions

array([1])

In [0]:
raw_output

array([[-0.7209952 ,  0.62882924]], dtype=float32)

In [0]:
pred,raw=model.predict(['Post Graduate Diploma in Management(Systems & Marketing), New Horizon College, Bangalore, KA in 2011'])

Features loaded from cache at cache_dir/cached_dev_bert_128_5_1


In [0]:
pred

array([4])

In [0]:
raw

array([[-0.9837271 , -0.22713107, -0.76111245,  0.06992629,  0.8009652 ]],
      dtype=float32)

In [0]:
pred1,raw1=model.predict(['Mainframe (Datacom, VSAM, CA-Dispatch,Control-M, Selcopy Z/os & Z/vm, PRD1, PRDT'])

Features loaded from cache at cache_dir/cached_dev_bert_128_5_1


In [0]:
pred1

array([4])

In [0]:
raw1

array([[-0.9837271 , -0.22713107, -0.76111245,  0.06992629,  0.8009652 ]],
      dtype=float32)

In [0]:
pred2,raw2=model.predict(['dobe AEM CQx5,6.0, Adobe CRX, Apache Sling, OSGi, Fatwire Content Management System, Macromedia Contribute 3, 4, and CS3, Homesite, and custom CMS and database solutions '])

Features loaded from cache at cache_dir/cached_dev_bert_128_5_1


In [0]:
pred2,raw2

(array([4]),
 array([[-0.9837271 , -0.22713107, -0.76111245,  0.06992629,  0.8009652 ]],
       dtype=float32))

In [0]:
dict= {
        "objective": [
            "objective",
			"professional objective",
            "career objective",
			"OBJECTIVE",
            "PROFESSIONAL OBJECTIVE",
            "CAREER OBJECTIVE",
			"Objective",
            "Professional Objective",
            "Career Objective"
			
        ],
        "courses": [
            "army courses",
			"ARMY COURSES",
			"Army Courses"
        ],
        "achievement": [
            "achievement",
            "honors & activities",
			"ACHIEVEMENT",
            "HONORS & ACTIVITIES",
			"Achievement",
            "Honors & Activities"
		],
        "summary": [
            "profile summary",
            "professional summary",
            "introduction",
            "summary",
			"PROFILE SUMMARY",
            "PROFESSIONAL SUMMARY",
            "INTRODUCTION",
            "SUMMARY",
			"Profile Summary",
            "Professional Summary",
            "Introduction",
            "Summary"
        ],
        "experience": [
            "work history",
			"employment",
			"employment history",
			"organisational experiance",
			"professional accomplishments",
            "experience",
            "summary of experiance",
            "experience synopsis",
            "organisational scan",
            "professional profile",
			"professional career",
            "summary",
			"career track",
            "experience",
            "experience summary",
			"industry experience",
            "work experience",
			"professional experience",
			"professional background",
            "current experience",
            "current organizational experience",
			"WORK HISTORY",
            "EXPERIENCE",
            "SUMMARY OF EXPERIANCE",
			"INDUSTRY EXPERIENCE",
            "EXPERIENCE SYNOPSIS",
            "ORGANISATIONAL SCAN",
            "PROFESSIONAL PROFILE",
			"PROFESSIONAL ACCOMPLISHMENTS",
			"ORGANISATIONAL EXPERIANCE",
			"EMPLOYMENT",
			"EMPLOYMENT HISTORY",
			"PROFESSIONAL CAREER",
			"PROFESSIONAL BACKGROUND",
            "SUMMARY",
            "EXPERIENCE",
            "EXPERIENCE SUMMARY",
            "WORK EXPERIENCE",
			"CAREER TRACK",
			"PROFESSIONAL EXPERIENCE",
            "CURRENT EXPERIENCE",
            "CURRENT ORGANIZATIONAL EXPERIENCE",
			"Work History",
            "Experience",
            "Summary Of Experiance",
            "Experience Synopsis",
            "Organisational Scan",
            "Professional Profile",
			"Professional Career",
			"Organisational Experiance",
			"Employment",
			"Employment History",
			"Career Track",
			"Industry Experience",
			"Professional Background",
			"Professional Accomplishments",
            "Summary",
            "Experience",
            "Experience Summary",
            "Work Experience",
            "Professional Experience",
            "Current Experience",
            "Current Organizational Experience"
        ],
        "education": [
            "education",
            "educational",
            "educational qualification",
            "academic qualification",
            "qualification",
			"EDUCATION",
			"EDUCATIONAL",
            "EDUCATIONAL QUALIFICATION",
            "ACADEMIC QUALIFICATION",
            "QUALIFICATION",
			"Education",
            "Educational Qualification",
            "Academic Qualification",
            "Qualification",
			"Qualifications",
			"qualifications",
			"QUALIFICATIONS",
			"Educated",
			"EDUCATED",
			"educated",
			"Professional Development",
			"PROFESSIONAL DEVELOPMENT",
			"professional development",
			"Credentials",
			"CREDENTIALS",
			"credentials",
			"Academic",
			"ACADEMIC",
			"academic"
        ],
        "skills": [
            "additional skills",
            "skills",
            "proficiencies and specialties",
            "skill set",
            "technical skill",
            "skills summary",
            "core competencies",
            "technical summary",
            "skills set",
            "personal skills",
            "additional it’s skills",
            "competency matrix",
            "areas of expertise",
			"ADDITIONAL SKILLS",
            "SKILLS",
            "PROFICIENCIES AND SPECIALTIES",
            "SKILL SET",
            "TECHNICAL SKILL",
            "SKILLS SUMMARY",
            "CORE COMPETENCIES",
            "TECHNICAL SUMMARY",
            "SKILLS SET",
            "PERSONAL SKILLS",
            "ADDITIONAL IT’S SKILLS",
            "COMPETENCY MATRIX",
            "AREAS OF EXPERTISE",
			"Additional Skills",
            "Skills",
            "Proficiencies And Specialties",
            "Skill Set",
            "Technical Skill",
            "Skills Summary",
            "Core Competencies",
            "Technical Summary",
            "Skills Set",
            "Personal Skills",
            "Additional It’s Skills",
            "Competency Matrix",
            "Areas Of Expertise"
        ],
        "training": [
            "trainings",
			"TRAININGS",
			"Trainings",
			"training",
			"TRAINING",
			"Training"
        ],
        "projects": [
            "professional memberships",
            "projects history",
            "project overview",
            "major projects",
            "project annexure",
			"PROFESSIONAL MEMBERSHIPS",
            "PROJECTS HISTORY",
            "PROJECT OVERVIEW",
            "MAJOR PROJECTS",
            "PROJECT ANNEXURE",
			"Professional Memberships",
            "Projects History",
            "Project Overview",
            "Major Projects",
            "Project Annexure"
        ],
        "links": [
            "links",
			"LINKS",
			"Links"
        ],
        "contacts": [
            "contacts",
			"CONTACTS",
			"Contacts"
        ],
        "positions": [
            "positions",
            "position",
			"POSITIONS",
            "POSITION",
			"Positions",
            "Position"
        ],
        "personal_details": [
            "personal details",
            "personal information",
            "personal profile",
			"PERSONAL DETAILS",
            "PERSONAL INFORMATION",
            "PERSONAL PROFILE",
			"Personal Details",
            "Personal Information",
            "Personal Profile"
        ],
        "contact_details": [
            "contact details",
			 "CONTACT DETAILS",
			 "Contact Details"
        ],
        "awards": [
            "awards",
            "awards & recognitions",
            "awards and recognition",
            "awards received",
			"AWARDS",
            "AWARDS & RECOGNITIONS",
            "AWARDS AND RECOGNITION",
            "AWARDS RECEIVED",
			"Awards",
            "Awards & Recognitions",
            "Awards And Recognition",
            "Awards Received"
        ],
        "certification": [
            "certifications",
            "certificates",
            "certifications",
            "professional certifications",
            "certification",
            "license and certifications",
			"CERTIFICATIONS",
            "CERTIFICATES",
            "CERTIFICATIONS",
            "PROFESSIONAL CERTIFICATIONS",
            "CERTIFICATION",
             "LICENSE AND CERTIFICATIONS",
			 "Certifications",
            "Certificates",
            "Certifications",
            "Professional Certifications",
            "Certification",
            "License And Certifications"
        ],
        "publication": [
            "publication",
            "publications",
			"PUBLICATION",
            "PUBLICATIONS",
			 "Publication",
            "Publications"
        ],
        "conference": [
            "conference",
            "conferences",
			"CONFERENCE",
            "CONFERENCES",
			 "Conference",
            "Conferences"
        ],
        "others": [
            "other",
            "additional information",
			"OTHER",
            "ADDITIONAL INFORMATION",
			"Other",
			"Additional Information"
        ]
    }

In [0]:
titles=[]

In [0]:
for val in dict.values():
  titles.append(val)

In [0]:
heading=[]

In [0]:
for val in titles:
  for text in val:
    heading.append(text)

In [0]:
len(heading)

254

In [0]:
heading=list(set(heading))

In [0]:
heading

['Educated',
 'links',
 'education',
 'AWARDS AND RECOGNITION',
 'Professional Memberships',
 'Career Objective',
 'Professional Background',
 'Position',
 'PROJECT ANNEXURE',
 'Summary Of Experiance',
 'Additional Information',
 'Professional Certifications',
 'Qualifications',
 'ADDITIONAL INFORMATION',
 'work experience',
 'position',
 'career objective',
 'honors & activities',
 'Summary',
 'SUMMARY',
 'personal profile',
 'PROFILE SUMMARY',
 'Competency Matrix',
 'other',
 'industry experience',
 'SKILLS SUMMARY',
 'Skills Summary',
 'CONTACT DETAILS',
 'Current Experience',
 'professional development',
 'EDUCATION',
 'objective',
 'PUBLICATIONS',
 'PROFESSIONAL CERTIFICATIONS',
 'Professional Summary',
 'PROFICIENCIES AND SPECIALTIES',
 'trainings',
 'Profile Summary',
 'SKILL SET',
 'academic',
 'POSITIONS',
 'Honors & Activities',
 'TECHNICAL SKILL',
 'certificates',
 'project annexure',
 'Industry Experience',
 'SKILLS SET',
 'LINKS',
 'organisational experiance',
 'MAJOR PROJ